package com.tibco.devtools.workspace.installer.standalone;

/**
 * Log the output of the constraint solver.
 * 
 * @param <M>	The type of message.  The actual output String
 * 	is generated by calling "toString()" on this object.
 * @param <E>	The enumeration of codes associated with logging.
 */
public interface LogOutput<E extends Enum<E>, M extends Object > {
	
	/**
	 * Log a fatal message.
	 * 
	 * @param code	The code associated with the message.
	 * @param message	The message to go with the error.
	 */
	void error(E code, M message);
	
	/**
	 * A warning associated with a problem
	 * 
	 * @param code	The code to associate with the message
	 * @param message	The message.
	 */
	void warning(E code, M message);
	
	/**
	 * Informative details to output along with other output
	 * 
	 * @param code	The code associated with the message.
	 * @param message	The message.
	 */
	void debug(E code, M message);
}	
